### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by FarazzShaikh** [FarazzShaikh/LunarLander#46]
`README.md` Does not reflect the games current state. Must make it such that it better represents the game and it's objectives.

**Comment by FarazzShaikh** [comment]
In progress, Started rewrite in #49 - b49cca9802f5f2694322c4fb4ba898ff9cba7cd1

**Comment by TheChosenSir** [comment]
I can undertake the rewriting of the Readme if you haven't done it already.

**Comment by FarazzShaikh** [comment]
@TheChosenSir Sure, but it requires a high level of understanding of the inner workings of the various systems. Go for it, ill help you along the way. But start it next week. We have more important features to make.

**Comment by FarazzShaikh** [comment]
closed in #87
