### ISSUE TITLE
Health rolling negative 

### ISSUE THREAD

**Issue by FarazzShaikh** [FarazzShaikh/LunarLander#56]
## Problem
Health is being subtracted from even after its zero. Shouldn't be a problem after death is implement but is a bug in current release.

## Bugged Lines
https://github.com/F28WP-Dubai-Group-6/LunarLander/blob/7d6d86f3c8bd8642cefc78ddaf18e783d5333d45/server/src/Game/Collision.js#L33

## Potential Solution
Guard the damage routine with an if block. Only allow subtraction of damage if the health is greater than 0.

**Comment by KishanBapodra** [comment]
i think i did do it in prev version willo fix this
