### ISSUE TITLE
Horizontal Velocity not killing player

### ISSUE THREAD

**Issue by FarazzShaikh** [FarazzShaikh/LunarLander#65]
# Problem
Horizontal Velocity not killing player. Terrain collision only checking vertical velocity, this means that if the player is cursing mostly horizontal with a very small vertical component, but a huge horizontal component, close the ground and impacts the ground, the player is not killed.

# Bugged Lines
https://github.com/F28WP-Dubai-Group-6/LunarLander/blob/29ac9c781f8eb5a61084b91d8893e49e1dce6d53/server/src/Game/Collision.js#L32

# Potential Solution
Modify the check so it also checks if the x component of velocity is above a certain threshold. If so, kill player.

**Comment by KishanBapodra** [comment]
Will handle it by today itself shouldn’t be a difficult problem.

**Comment by FarazzShaikh** [comment]
@KishanBapodra you know the drill.
